#!/bin/sh

cd /root/oboro
PATH=./:$PATH

L_SRV=login-server_sql
C_SRV=char-server_sql
M_SRV=map-server_sql

print_start() {
#    more << EOF
echo ""
echo "            (c) 2003 Athena Project"
echo "              j-isaac10@hotmail.com"
echo ""
#EOF
}

check_files() {

    for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
        if [ ! -f ./$i ]; then
            echo "$i [ERROR]encontrado."
            echo "Procede a compilar."
            exit 1;
        fi
    done

#    more << EOF
echo "[LISTO] ningun error encontrado"
#EOF
}
    

case $1 in
    'iniciar')
        print_start
        check_files

        exec ./${L_SRV}&
        exec ./${C_SRV}&
        exec ./${M_SRV}&

        echo "Iniciando"
;;
    'parar')
        ps ax | grep -E "${L_SRV}|${C_SRV}|${M_SRV}" | awk '{print $1}' | xargs kill
;;
    'compilar')
	chmod +x configure && ./configure  --enable-64bit && make clean && make sql 2>&1 | tee -a /root/Desktop/Logs/compile-$DATE.log
;;
    *)
        echo "[ ISAACHJK ] ./- { iniciar | parar | compilar }"
;;
esac