{ "reloadgrfintegrity",          99,   atcommand_reloadgrfintegrity },
{ "reloadharmony",               99,   atcommand_reloadharmony },
{ "showautoban",                 99,   atcommand_showautoban },
{ "liftautoban",                 99,   atcommand_liftautoban },
{ "netinfo",                     99,   atcommand_netinfo },
{ "macban",                      99,   atcommand_macban },
{ "liftmacban",                  99,   atcommand_liftmacban },
{ "showmacban",                  99,   atcommand_showmacban },

